name: XVideos Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: "XVideos video URL"
        required: true
        type: string

permissions:
  contents: write

jobs:
  download-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y yt-dlp ffmpeg coreutils

      - name: Create folders
        run: |
          mkdir -p downloads
          mkdir -p parts

      - name: Download video
        run: |
          yt-dlp \
            --no-playlist \
            -o "downloads/video.%(ext)s" \
            "${{ github.event.inputs.url }}"

      - name: Find downloaded file
        id: file
        run: |
          FILE=$(find downloads -type f | head -n 1)
          echo "filepath=$FILE" >> $GITHUB_OUTPUT

      - name: Split into 95MB parts
        run: |
          split -b 95M \
            "${{ steps.file.outputs.filepath }}" \
            "parts/video.part."

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: split-${{ github.run_id }}
          name: "Split Video ${{ github.run_id }}"
          files: parts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save release link
        run: |
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/split-${{ github.run_id }}"
          echo "$(date) -> $RELEASE_URL" >> downloads/history.txt

      - name: Commit history
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add downloads/history.txt
          git commit -m "Add release link"
          git push
