name: XVideos to Pages

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Video URL"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y yt-dlp ffmpeg

      - name: Download video
        run: |
          mkdir video
          yt-dlp \
          --no-playlist \
          -o "video/video.%(ext)s" \
          "${{ github.event.inputs.url }}"

      - name: Split video
        run: |
          mkdir public
          FILE=$(find video -type f | head -n 1)
          split -b 95M "$FILE" public/video.part.

      - name: Create index
        run: |
          echo "<h2>Video Parts</h2>" > public/index.html
          for f in public/video.part.*; do
            name=$(basename $f)
            echo "<a href=\"$name\">$name</a><br>" >> public/index.html
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
